version: '3.7'
services:
  flask-app:
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
    - mysql
    environment:
            USERNAME: ${USERNAME}
            PASSWORD: ${PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
  mysql:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: flask-db
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - flask-app
